version: '3'
services:
  web:
    build: 
        context: web
        dockerfile: Dockerfile
    ports:
        - "127.0.0.1:8080:8080"
    depends_on:
    - db
    networks:
    - backend-net

  db:
    build: 
        context: db
        dockerfile: Dockerfile

    networks:
    - backend-net

networks:
  backend-net:
    driver: bridge