version: '3'
services:
  web:
    build: 
        context: web
        dockerfile: Dockerfile
    ports:
        - "0.0.0.0:8080:8080"
    depends_on:
    - db
    networks:
    - backend-net

  db:
    build: 
        context: db
        dockerfile: Dockerfile

    #adds the location for the stored data to a relative path HOST:CONTAINER
    volumes:
        - ./postgres_data/data:/var/lib/postgresql/data

    networks:
    - backend-net

networks:
  backend-net:
    driver: bridge
